# Generated by Django 5.1.4 on 2024-12-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCarne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecebimentoCarne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('code', models.IntegerField(db_index=True, help_text='Codigo do fornecedores', primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(help_text='Nome', max_length=100, unique=True, verbose_name='Nome Fornecedor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cnpj', models.CharField(help_text='CNPJ', max_length=11, unique=True, verbose_name='CNPJ')),
                ('status', models.BooleanField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_system.category')),
            ],
        ),
    ]
