# Generated by Django 5.1.4 on 2024-12-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_analisecarne_enderecofilial_enderecofornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(help_text='CNPJ', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
    ]
