# Generated by Django 5.1.4 on 2024-12-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_alter_fornecedores_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo', max_length=20),
        ),
    ]
